# Default values for kinoreel backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kinoreel/backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: kinoreel-backend
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
